NeuralAnalysis/PyalData

pyaldata/tools.py
pyaldata/utils.py

Add decorator to implicitly copy the first argument

---

pyaldata/tools.py
pyaldata/utils.py

I'm not a fan of writing out the nested for loop twice
Fixes #5

Add first version of add_firing_rates function

---

pyaldata/tools.py

Add add_gradient function

---

pyaldata/tools.py
pyaldata/utils.py

1. Renamed `concatTrials` to `concat_trials`
2. Updated the code to take advantage of pandas and numpy.

Update function for concatenating trials

---

pyaldata/tools.py
pyaldata/utils.py

- center
- z-score
- sqrt-transform
- "zero-normalize"
- "center-normalize"
- "soft-normalize"
They can be used on their own or through the `transform_signal` function.
Fixes #9

Add a few transformations

---

pyaldata/tools.py

Merge signals (e.g. spikes from M1 and PMd) that share time coordinates.

Add merge_signals function

---

pyaldata/utils.py

@catiafortunato Do we maybe want to call it `get_sig`?
Fixes #14

Add get_signals function

---

pyaldata/utils.py

This commit was already included in multiple pull requests.

Add get_time_varying_fields function

---

pyaldata/tools.py
pyaldata/utils.py

Fixes #21 
(cherry-picked get_time_varying_fields from another branch)

Trial averaging

---

pyaldata/tools.py

Replicates aliasTDfields function. Split into rename_fields and copy_fields. 
Solves #6

Add rename_fields and copy_fields

---

pyaldata/tools.py

add function to concatenate trialdata structs

---

pyaldata/tools.py

Correctly resolve `win`, `std` and `hw`.

Fix add_firing_rates

---

pyaldata/tools.py
pyaldata/utils.py

`binTD` does some checks on the `idx` fields. I'm not sure what those are and if they are necessary using this method. @catiafortunato 
Fixes #7

Add combine_time_bins function

---

pyaldata/utils.py

It doesn't check for the shapes, I think the "ValueError: all input arrays must have the same shape" from numpy is informative enough.
Fixes #15

Add get_sig_by_trial function

---

pyaldata/tools.py

Add functions remove_low_firing_neurons and get_average_firing_rates

---

pyaldata/utils.py

Use np.concatenate in concat_trials

---

pyaldata/tools.py

Add subtract_cross_condition_mean function

---

pyaldata/__init__.py

Export every function at the module level

---

pyaldata_demo.ipynb

Doesn't run locally because it uses data from my computer.
We should upload an example dataset here and use that.

Add notebook for illustrating PyalData's functionality

---

pyaldata/utils.py

Update extract_interval_from_signal to handle both 2D and 1D signals

---

pyaldata/utils.py

Load v7.3 mat files using mat73 instead of scipy

---

pyaldata/tools.py

Update combine_time_bins to use get_time_varying_fields

---

pyaldata/tools.py
pyaldata/utils.py

Drop trials where restrict_to_interval would not work and warn the user

---

pyaldata/tools.py

Added an `epoch_fun` argument to `restrict_to_interval` and made `start_point_name` optional.
We've already generated a function from the arguments and passed that internally in `utils.extract_interval_from_signal`. Now the user has the option to pass their function to `restrict_to_interval` directly. This is necessary in cases where the `idx_` fields store arrays instead of single indices (because there are multiple reaches in a trial) and one can do things like:
```python
def after_go_cue(trial, i):
return slice(trial.idx_go_cue[i], trial.idx_go_cue[i]+50)
first_reach_td = restrict_to_interval(df, epoch_fun = lambda trial: after_go_cue(trial, 0))
```

Restrict to epoch using an "epoch function"

---

pyaldata/tools.py

Average signal in time in each trial, then stack them into an `n_trials` x `n_features` array

Add stack_time_average function

---

pyaldata/utils.py

Might fix #111 
@raeedcho can you check if it works as intended?

Use pandas's missing data features

---

pyaldata/utils.py

Reverts mattperich/PyalData#113
Reverting as it introduced problems with simple querying like `select_trials(df, "whatever_field != 20.")` if `whatever_field` has the `pd.NA` values.

Revert "Use pandas's missing data features"

---

pyaldata/utils.py

Following @babaf's suggestion. Runs around 4x faster on my computer.
Also changes padding behavior from zero-padding to "reflect".
Fixes #101

Speed up smoothing by using `scipy.ndimage.convolve1d`

---

pyaldata/utils.py

Fixes https://github.com/mattperich/PyalData/issues/116

fix(norm_gauss_window): increase length of gaussian window to 10 standard deviations to avoid jaggedness

---

pyaldata/interval.py

Addresses https://github.com/NeuralAnalysis/PyalData/issues/134

fix(iss134): fix bug in restrict_to_interval that produces strange behavior with epoch_fun

---

pyaldata/movement_onset_and_peak.py

The only real change is `tools.add_gradient` -> `signals.add_gradient` and `tools.add_norm` -> `signals.add_norm`

Fix import of add_gradient and add_norm, and format

---

pyaldata/integrity_checks.py
pyaldata/tools.py
tests/test_trial_average.py

I think some behavior changed in pandas that broke functionality.

Update time_average and add tests

---

pyaldata/array_utils.py
pyaldata/data_cleaning.py
pyaldata/df_utils.py
pyaldata/dim_reduction.py
pyaldata/extract_signals.py
pyaldata/firing_rates.py
pyaldata/interval.py
pyaldata/io.py
pyaldata/movement_onset_and_peak.py
pyaldata/regression.py
pyaldata/signal_transformations.py
pyaldata/smoothing.py
pyaldata/tools.py
pyaldata/utils.py

Add type hints throughout most of the code and fix some PEP complaints.

Add type hints

---

.github/workflows/ruff.yml
pyaldata/__init__.py
pyaldata/array_utils.py
pyaldata/cmp.py
pyaldata/data_cleaning.py
pyaldata/df_utils.py
pyaldata/dim_reduction.py
pyaldata/extract_signals.py
pyaldata/firing_rates.py
pyaldata/interval.py
pyaldata/io.py
pyaldata/movement_onset_and_peak.py
pyaldata/regression.py
pyaldata/signal_transformations.py
pyaldata/signals.py
pyaldata/smoothing.py
pyaldata/tools.py
pyaldata/utils.py
pyproject.toml

Enforce formatting and standards so that we don't have to think about that ourselves.
- Adds a github action that checks the code with ruff
- Fixes the code such that this check passes now

Add github action to lint with ruff
