pyaldata/utils.py
It creates just 1 dataframe.
I might like `mat2df` even better
=> Rename mat2dataframes to mat2dataframe

pyaldata/Tools.py, pyaldata/utils.py
Rewrote `utils.smooth_data`
Kept the same first arguments not to break Catia's existing code.
Can handle 1D and 2D arrays.
Switches to scipy.signal.convolve with the method="same" to keep the original size of the arrays.
Can be used with a smoothing window, standard deviation or half-width.
=> Rewrite smoothing

pyaldata/tools.py
Using smooth_signals without a second argument (aka using the default
std of 0.05 seconds) threw an assertion error.
This fixes that by properly resolving the std and hw arguments.
Fixes #31
=> Fix smooth_signals

pyaldata/tools.py
Adds a new field with `_norm` appended to the original signal's name.
Fixes #13
=> Add add_norm function

pyaldata/tools.py
- `fit_dim_reduce_model` fits a model to a given signal in the data and returns the model
- `apply_dim_reduce_model` applies a fitted model to a given signal and adds a new field to the dataframe
- `dim_reduce` fits a model, applies it to every trial, and adds a new field
Fitting can be done on just training trials.
`model` can be anything that implements `.fit(X)` and `.transform(X)` methods where `X` is a `samples x features` array. This way we don't have to have include every method we might use, just pass a model object to this function.
I left the `utils.DimReduce` function to not break existing code. I noticed that it saved model parameters in a dict. That is replicated in `dim_reduce` by a `return_model` argument to return the fitted model along with the data if we want to use it …
=> Add functions for dimensionality reduction

pyaldata/utils.py
I decided that the `shift_idx_fields` should be explicitly given instead of setting it to true by default so that we are always aware that it's happening.
Existing code will have to be adapted accordingly.
Fixes #24
=> Add backshift_idx_fields function and add it to mat2dataframe

pyaldata/tools.py, pyaldata/utils.py
Add functionality to extract parts of trials.
Probably the main addition is `restrict_to_interval`
Fixes #22 
Also, I added  a `get_time_varying_fields` that tries to identify every field in the dataframe that seems to have a time dimension.
=> Restrict time to interval

pyaldata/tools.py, pyaldata/utils.py
Fix `mat2dataframe` to not need the data to be named trial_data.
Fixes #49
=> Fix mat2dataframe

pyaldata/tools.py
We can average across all trials by setting `condition` to `None`, but it has to be explicitly specified (not default value).
Fixes #63
=> Add option not to group in trial_average

pyaldata/tools.py
`verbose=True` prints a message about how many low-firing neurons were removed
Fixes #68
=> Add verbose option to remove_low_firing_neurons

pyaldata/__init__.py, pyaldata/regression.py
Introduce 3 functions for using regression models on the TrialData format: `fit_regressor_model`, `apply_regressor_model`, `regress`.
Ideally it works with any model that defines a `.fit` and a `.predict` method.
=> Add functions for using regression models

pyaldata/tools.py
If the input is 1D, reshape it to 2D, do everything as normal, then get rid of the extra dimension by squeezing.
Fixes #80
=> Make rebin_array work for 1D arrays

pyaldata/tools.py
Transforming signals one-by-one was annoying. Now we can do `df = center_signal(df, ["M1_rates", "PMd_rates"])`
`transform_signal` and co. work the same way.
=> Extend transformation functions to handle multiple columns

pyaldata/utils.py
So far the code assumed the dataframe would be the first positional argument, but potentially it can be passed as `trial_data = df`. Now that should work as well.
Fixes #84
=> Handle passing dataframe by keyword in copy_td

pyaldata/tools.py, pyaldata/utils.py, setup.py
The `trial_average` function was broken on newer versions of pandas
because of changes introduced in pandas 1.2.0 (see https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.2.0.html#consistency-of-dataframe-reductions).
Update it to work with the new behavior of `pd.DataFrame.mean`
=> Fix trial_average and bump required pandas version

pyaldata/tools.py, pyaldata/utils.py
Include fields ending with "rates" when looking for a default `ref_field` and always take an optional `ref_field` argument where `get_time_varying_fields` is used.
Fixes #89
=> Fix time varying fields

pyaldata/__init__.py, pyaldata/movement_onset.py, pyaldata/movement_onset_and_peak.py, pyaldata/tools.py
Using scipy is a tiny bit faster than the method borrowed from TrialData, but they give the same result.
In some data sets there are trials where this doesn't give exactly the same answer as the saved `idx_movement_on` fields. I assume they were exported with different settings.
Fixes #12
=> Add get_movement_onset (and get_on_idx) function(s)

pyaldata/tools.py
In a lot of cases we want to normalize the change in the signal by the length of the timestep (e.g. when calculating velocities from positions)
=> Add option to normalize gradient in `add_gradient`

pyaldata/tools.py
I think @JoannaChang warned me about this. Only touch the unit guide if it actually exists.
=> Don't require unit guide in `remove_low_firing_neurons`

pyaldata/utils.py
In order to avoid weird errors, clean fields that store scalars as 0D arrays and fields that store integers as floats when loading .MAT files.
=> Clean fields when loading

pyaldata/movement_onset_and_peak.py
Calculating movement onset depends on these values, so instead of throwing errors, just add them and proceed.
=> Add 'vel' and 'vel_norm' when calculating movement onset

pyaldata/__init__.py, pyaldata/array_utils.py, pyaldata/extract_signals.py
- `split_array` splits an array along its first dimension into chunks of given lengths
- `reverse_concat` uses `split_array` to split a concatenated signal back to smaller arrays for each trial
=> Add split_array and reverse_concat functions

pyaldata/utils.py, tests/test_determine_ref_field.py, tests/test_get_time_varying_fields.py, tests/test_get_trial_length.py
Change the behavior such that:
- in `get_trial_length` if no explicit reference field is given, throw an error if not all spikes / rates fields have the same length because then the reference length is ambiguous
- same for `get_time_varying_fields`: without an explicit reference field, all spikes / rates fields have to be the same length on all trials
- `get_time_varying_fields` warns if there is a field that has arrays as its elements and has the same length on the first dimension as the reference field on at least 80% of trials
- the old behavior of `get_time_varying_fields` (identifying candidate fields on the first trial and throwing an error if they don't match on other trials) can be accessed passing `strict_criterion=False`
=> Improve `get_time_varying_fields`

pyaldata/__init__.py, pyaldata/utils.py, tests/test_get_trial_length.py
- `get_trial_lengths` returns an array of trial lengths in the dataframe
- `get_trial_length` can be applied to dataframes. It returns a single value if all the trials have the same length, and raises an error otherwise
=> Add `get_trial_lengths` and extend `get_trial_length` to handle dataframes

pyaldata/smoothing.py
scipy moved the window functions to `scipy.signal.windows` and deprecated `scipy.signal.gaussian`
=> scipy.signal.gaussian was moved to scipy.signal.windows.gaussian

pyaldata/data_cleaning.py, tests/test_data_cleaning.py
`clean_0d_array_fields` only checked the first element of a column.
@martinesparza has a use case where some elements of a column are 0D arrays, so scalars, some 1D arrays.
If the first element is a 0D array, but the others aren't, checking the element's `ndim` throws an error.
This fixes that by only converting columns where all elements are 0D arrays.
=> Require all elements of a field to be 0d arrays for converting to scalar
